Update to make the button a metabox Gutenberg compatible
electricbookworks/paged-wp pull request #6
Opened 2019-06-07 23:19 UTC by typometre

Having a metabox is better to make it compatible with Gutenberg editor and to make it easier to provide more option in future version.
1bf81dc

2019-06-08 10:36 UTC, jonathanbossenger commented
@arthurattwell I'd appreciate your thoughts on this. While converting the buttons to being part of a meta box does make it immediately Gutenberg compatible, it does move away from your original requirement of having the buttons close to the publish controls.

2019-06-08 10:48 UTC, typometre commented
On Classic editor, you can move the metabox where you want. Could be higher than the publish/update wordpress metabox. On Gutenberg you can move the metabox but only to arrange the order with other site specific metabox, you can't place it before Wordpress default ones. In order to provide future options in the panel (like select or write css option), the metabox panel seems to me the way to go.

2019-06-08 11:36 UTC, jonathanbossenger commented
Unless the requirement is to add the controls in the same place as the publish or preview buttons, in a similar way to which Jetpack adds it's button in the block editor, which may provide for a better user experience.

http://tinyurl.com/y394pudl

2019-06-08 12:13 UTC, typometre commented
That's a sidebar plugin. It's a way to open a new panel in sidebar. Could be useful if eventually there will be too many options and need space for them. But it actually isn't a way to add a button in itself, but a button to open a complete new sidebar panel where you would place the paged preview button. Doesn't seems to help as it would require more steps to go to the paged preview button. https://developer.wordpress.org/block-editor/tutorials/plugin-sidebar-0/
There is plugins that adds buttons at that top place which aren't sidebar plugin (as Elementor add an edit with elementor on the left side) but this kind of things seems undocumented on official gutenberg docs.

2019-06-08 13:03 UTC, jonathanbossenger commented
@typometre the type of button is not the point I was trying to make, the initial requirement for the Paged Preview button was to have it appear as close to the publish buttons as possible. I was merely using the Jetpack button as a visual example of this in the block editor. As you've pointed out, other plugins have added their own buttons to the block editor top bar and if the requirement remains the same, it's worth investigating it, undocumented or not.

2019-06-08 15:17 UTC, arthurattwell commented
Thanks, @typometre! Gutenberg compatibility will be great. Thanks, @jonathanbossenger, for engaging with this. We're planning a sprint on this in the coming weeks and will be able to make a call on this then, along with improvements we have planned in #5.

2019-09-05 08:32 UTC, jonathanbossenger requested changes
Finally, besides moving the main.css from being an external resource to being bundled with the plugin, there seem to be a lot of other asset files that are not necessary for the plugin code to function. Could you please omit them from the PR, thanks

2019-09-05 08:32 UTC, jonathanbossenger commented on README.md
> +- This fork work with the Classic or Gutenberg editor.
We can remove this.

2019-09-05 08:32 UTC, jonathanbossenger commented on paged-wp.php
> +add_action( 'add_meta_boxes', 'wppaged_register_meta_boxes' );
Please register the action before the callback function, that way it's easier to see which function is being called by which action hook.

2019-09-05 08:32 UTC, jonathanbossenger commented on paged-wp.php
> +    add_meta_box( 'meta-box-paged', __( 'Paged Preview', 'textdomain' ), 'wppaged_my_display_callback', 'post', 'side', 'high',
Can we rename the callback to something more verbose like wppaged_paged_meta_box_display

2019-09-05 08:32 UTC, jonathanbossenger commented on paged-wp.php
> +    // Display code/markup goes here. Don't forget to include nonces!
Please ensure to add nonce checks for security

2019-09-05 08:32 UTC, jonathanbossenger commented on paged-wp.php
> +    // Save logic goes here. Don't forget to include nonce checks!
Please include the save post logic, as well as nonce checking for security.

2019-09-05 08:33 UTC, jonathanbossenger commented
Hi @typometre, after discussion with @arthurattwell I've review the PR and requested some changes. Please let us know if you can complete these changes so that we can merge in this PR. Thanks

2019-09-05 08:35 UTC, jonathanbossenger commented on paged-wp.php
> +    // Save logic goes here. Don't forget to include nonce checks!
FYI if there is no intention of actually doing anythnig on the save post, we can leave out this function call

2019-09-10 10:46 UTC, jonathanbossenger commented
Hi @typometre I appreciate that open source time is volunteer time, so I just wanted to check in to see if you've seen the review I posted? Do you think you are in a position to be able to make the changes?

2019-09-11 07:02 UTC, typometre commented
I was busy and see this just now that I try to read my unread emails. Ok will have a look this week-end.

2019-09-11 07:03 UTC, jonathanbossenger commented
No problem, thanks for the update.

2019-09-24 06:52 UTC, merged